language: d
sudo: false
branches:
  only:
  - master
addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev
script:
- dub build --config="ddox" -b ddox
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/docs"
  github_token: "$GITHUB_API_KEY"
  on:
    branch: master
