language: d
env:
  global:
  - secure: "Pb64DQ5wtyLFkMlCVWeDj5AJ4f0vkkZmnQSWV8zLnz/ir4Kuese0G54+VGYyJR2iE9bQvqMDnpMO9LyvMVgL2k+LX2z1CLI/uj0QLMnGwS/n9hMDI5Q5qGZGEA9W1nIirpy/r+AY9epe2G18O/oSAiV7cb1Ou3b5V8Kz7+8QTmhxmFIpbQRA3jwC4BB4fZjjCL5xdOhP4LGo3svFD3unN2EARwtcq/v21rn+A/2I1bxbTNrsBpExw8ni0hQuiLRZe6m5xbAvUjlnEbi0y/AxADM193uRqFRt6YtX2pgA1+orSZVgXLeAXVOFPQwtWnysKhCNKFK9ee9JCozTlkW7yqpQOEW/gqesZIDLHbqzExYs0xlxVRdY8IZQX+46YtNFh3caqpav67nRug2Xb7AkJZwXBdZLiyiENN4ZQ3o89ok1nI547m5qR2CLK65ahVtaniokcVH7jPK9BOpPq4oWyyo0D4l+IcJpXnwq363scY+S5yH/nvjWoeXWoMnKxlQGOtG1eoMT4E7cyo6Q/S9bpEwq3UCFlxSAj7zjgEkZ88vo6ZiaCSztdwqP5GKQkj5I12qA9K5oj08oqkUSg6746rqY3n544UYYI6MMZA6caedqlWxaHDxW/t3PN+BKOrHpn2c6WkwTXL4NbX3GDfFs8AcY0MFH+0/gNmeHyTUGh6U="
sudo: false
branches:
  only:
  - master
addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev
script:
- dub build --config="ddox" -b ddox
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/docs"
  github_token: "$GITHUB_API_KEY"
  on:
    branch: master
