language: d
env:
  global:
    secure: kUbY0hMEoTmFCIZ/EUdaIEQ9BAc7EQr/KgKT99AQGY7IGF1o/h6hu/HqL2lMrG5l4AmojOf4f0TJg8fFVLOZpF9L2YuAZbOuEZibX93GEkvSEjK+dnPXZ5fc7e3kvlZdvbyV7EzKhjUqrLctK+D5P9nIxadJKq3Q30E+oZv2APLITD6eo/ViW0GvRBFvwcmwQF6aOvk+JaaX15r/PB3Fbfl8Ozvy/AWM/e4emwW9nWJAc4sIo0XzBGNgZjoyq/AFoyQ8F8+EZGsxu3e3l54DiX/6nBFBFDJ+rsQwKLCW0ktdPz1mJJJwHI+onqdfEhbaLwtZNIPxEARYwAhSNkFeZWFVbqo0nnrwR4/BhBWmlERwCcnsR5ADjBFj9XMsP8emE8u1vuAkjWSMCjtKGLQr26HsR5Wf5Rithh2C+3gr0Q9nyMNpXmLqcKeMz7tEBn/LTTVsNRAtFmPhhXUWdTIrYnaR2/CNBgqJwYK8uI3t+cwgLWuOE5x38MsRfQqCOGnIRk/vl7TH9cPmvCJWjyZ0w9objoHQIPmr4qp7aFnIXkCDea/pezD+DTYjT4eLXnUfe5mek6pp97SiIGj9qL1PhajxozI0zUY6ySSCbUNi2RcheDew0x6uFIf2LuI4mDeftGh9NvPuB0MXX4Pcj4ggg4frg3Awlf9qObenvTWA2ow=

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev

# Build steps
script:
#  - dub test --compiler=${DC}  # Default: run unittests
   - dub build --config="ddox" -b ddox

# Deploy using travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs
  github_token: $GITHUB_API_KEY
  on:
    branch: master
