language: d
env:
  global:
  - secure: SMezbmVmN99lR6j3W8YUMs5KhqlzMPZ82OYh/jLNj3L3Fj3FMNwd4dRAArBcOD0Gna0ALL4cKicWk3LL+ypWOJGys+0zjgwvkVTsBm023gmtvk8/pKnjDhHJBGMWtw5AbbMAGv1jaff5XgBqK8AjrtFZjZcOL0klnvsncE5nvRYuw3DXdaX6qAv5FDFaIjK9mbqShGoHcTmHXz9gKh2riOrTB1gkhpLrh6z20+q87vru46DH9y2TFyb+5jFY76s1mOv0fZ9ygZW2fyHY55A9Zu33LxIPHRfamadOvZpeRLtuhzVb67qXYmJqwPKjU73zHn99ar9iRaIaYFRsQQoI+idgH++kGifWLP53hkyEJdujUIT0YB3DFaY/0ePUHN/e5Ox0xsOhSwzk7ErNoPoSkHHAkULEbJgxTLNCjV/P8Pdx9/b87tR7IsSXZMO7gia3sQ6pw8b6NoTQ8RUz2navQksNHgk5vTlX+XMfeMU0d7GmaWBPe6K2qmkgiDj3FCDrhqrDJN2OzQuhQ02B5yc/ZiHa0cnAdbdjQmHKGu47ypDy51XSqD3qnunhtY2xzfI2Qp6OY1j4i1GDLf4PVR9UBZr11uKh3fLY8KPbZ1q7LXo9E3l+LbqYvJ56wJrN+3bwq9cebg2C+Gsuc0n+1rlFF1VDl/XmQavOHB40QxdhIBw=
sudo: false
branches:
  only:
  - master
addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev
script:
- dub build --config="ddox" -b ddox
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/docs"
  github_token: "$GITHUB_API_KEY"
  on:
    branch: master
